### ISSUE TITLE
alguns cursos tem formatos diferentes de matrícula

### ISSUE THREAD

**Issue by RicardoBucard** [diogosmendonca/sisgee#16]

**Comment by RicardoBucard** [comment]
permitir busca de matrículas que contenham apenas números e formatos que tenham mais caracteres

**Comment by diogosmendonca** [comment]
Preciso de um exemplo concreto para que este issue possa ser feito.

**Comment by RicardoBucard** [comment]
Matrícula 12217130176 Curso de Gestão em Turismo
Aluna Ana Neri Gaspar Barreto

**Comment by diogosmendonca** [comment]
Exemplos de matrículas que o sistema não aceita:
1300910INFODIST
1801774TELEINT

**Comment by diogosmendonca** [comment]
@RicardoBucard favor implantar a correção em produção e testar em produção. Depois de testar em produção, se estiver tudo ok pode fechar o issue.

**Comment by diogosmendonca** [comment]
@RicardoBucard podemos fechar este issue?
